<!-- Subs.Ext\Tools\Rating.WPF\Rating.WPF.csproj -->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <OutputType>WinExe</OutputType>
	  <TargetFramework>net6.0-windows</TargetFramework>
	  <UseWPF>true</UseWPF>
	  <AssemblyName>RatedSubs</AssemblyName>
	  <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
	  <AssemblyVersion>0.1.0.0</AssemblyVersion>
	  <FileVersion>0.1.0.0</FileVersion>
	  <InformationalVersion>0.1.a</InformationalVersion>
	  <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
	  <Deterministic>false</Deterministic>
	  <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
	  <ApplicationIcon>Resources\AppIcon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Resources\AppIcon.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.7.1" />
    <PackageReference Include="Prism.Unity" Version="8.1.97" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Converters\" />
  </ItemGroup>
  <ItemGroup>
    <None Update="settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>